apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-user
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: nodecontainer
          image: containerimage:latest
          ports:
            - containerPort: 8000
